# coding: utf-8

# flake8: noqa
"""
    Unix Timestamp Converter API

    An API to convert between Unix timestamps and human-readable date strings

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from api_sdk.models.convert_timestamp200_response import ConvertTimestamp200Response
    from api_sdk.models.convert_timestamp_s_parameter import ConvertTimestampSParameter
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from api_sdk.models.convert_timestamp200_response import ConvertTimestamp200Response
from api_sdk.models.convert_timestamp_s_parameter import ConvertTimestampSParameter

""",
            name=__name__,
            doc=__doc__,
        )
    )
