# coding: utf-8

# flake8: noqa

"""
    Unix Timestamp Converter API

    An API to convert between Unix timestamps and human-readable date strings

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "TimestampApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ConvertTimestamp200Response",
    "ConvertTimestampSParameter",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from api_sdk.api.timestamp_api import TimestampApi as TimestampApi
    
    # import ApiClient
    from api_sdk.api_response import ApiResponse as ApiResponse
    from api_sdk.api_client import ApiClient as ApiClient
    from api_sdk.configuration import Configuration as Configuration
    from api_sdk.exceptions import OpenApiException as OpenApiException
    from api_sdk.exceptions import ApiTypeError as ApiTypeError
    from api_sdk.exceptions import ApiValueError as ApiValueError
    from api_sdk.exceptions import ApiKeyError as ApiKeyError
    from api_sdk.exceptions import ApiAttributeError as ApiAttributeError
    from api_sdk.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from api_sdk.models.convert_timestamp200_response import ConvertTimestamp200Response as ConvertTimestamp200Response
    from api_sdk.models.convert_timestamp_s_parameter import ConvertTimestampSParameter as ConvertTimestampSParameter
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from api_sdk.api.timestamp_api import TimestampApi as TimestampApi

# import ApiClient
from api_sdk.api_response import ApiResponse as ApiResponse
from api_sdk.api_client import ApiClient as ApiClient
from api_sdk.configuration import Configuration as Configuration
from api_sdk.exceptions import OpenApiException as OpenApiException
from api_sdk.exceptions import ApiTypeError as ApiTypeError
from api_sdk.exceptions import ApiValueError as ApiValueError
from api_sdk.exceptions import ApiKeyError as ApiKeyError
from api_sdk.exceptions import ApiAttributeError as ApiAttributeError
from api_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from api_sdk.models.convert_timestamp200_response import ConvertTimestamp200Response as ConvertTimestamp200Response
from api_sdk.models.convert_timestamp_s_parameter import ConvertTimestampSParameter as ConvertTimestampSParameter

""",
            name=__name__,
            doc=__doc__,
        )
    )
