name: 'Setup Python Environment'
description: 'Sets up Python and installs dependencies'
runs:
  using: "composite"
  steps:
    - name: "Install uv"
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: "Install dependencies"
      run: make install
      shell: bash
