# coding: utf-8

"""
    Unix Timestamp Converter API

    An API to convert between Unix timestamps and human-readable date strings

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_sdk.models.convert_timestamp200_response import ConvertTimestamp200Response

class TestConvertTimestamp200Response(unittest.TestCase):
    """ConvertTimestamp200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConvertTimestamp200Response:
        """Test ConvertTimestamp200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConvertTimestamp200Response`
        """
        model = ConvertTimestamp200Response()
        if include_optional:
            return ConvertTimestamp200Response(
            )
        else:
            return ConvertTimestamp200Response(
        )
        """

    def testConvertTimestamp200Response(self):
        """Test ConvertTimestamp200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
