# coding: utf-8

"""
    Unix Timestamp Converter API

    An API to convert between Unix timestamps and human-readable date strings

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_sdk.models.convert_timestamp_s_parameter import ConvertTimestampSParameter

class TestConvertTimestampSParameter(unittest.TestCase):
    """ConvertTimestampSParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConvertTimestampSParameter:
        """Test ConvertTimestampSParameter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConvertTimestampSParameter`
        """
        model = ConvertTimestampSParameter()
        if include_optional:
            return ConvertTimestampSParameter(
            )
        else:
            return ConvertTimestampSParameter(
        )
        """

    def testConvertTimestampSParameter(self):
        """Test ConvertTimestampSParameter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
