# coding: utf-8

"""
    Unix Timestamp Converter API

    An API to convert between Unix timestamps and human-readable date strings

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_sdk.api.timestamp_api import TimestampApi


class TestTimestampApi(unittest.TestCase):
    """TimestampApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TimestampApi()

    def tearDown(self) -> None:
        pass

    def test_convert_timestamp(self) -> None:
        """Test case for convert_timestamp

        Convert Unix timestamp or date-time string
        """
        pass


if __name__ == '__main__':
    unittest.main()
